### ISSUE TITLE
Dependencies workflow?

### ISSUE THREAD

**Issue by miguelslp** [jaredgorski/eleventy-njk-unpkg-inliner#1]
Which workflow do you suggest for packages with their own npm dependencis?

**Comment by jaredgorski** [comment]
Hi Miguel,

Good question. Normally, packages should have some file available on unpkg that contains all of the inlined/compiled/minified code. Often, this is something like `dist/index.js`, `build/index.browser.js`, or maybe `index.min.js` if it's minified. This is the kind of file meant to be targeted by the inliner here. In other words, ideally those vendors are already exposing a compiled file with all dependent code imported (and perhaps minified and tree-shaken) that can serve as your "entrypoint".

If this file isn't available on unpkg, it seems you would either need to inline the dependencies manually (which could be tedious... kind of defeats the convenience factor here) or find some way to compile that package with all dependent code inlined and then publish to NPM yourself in order to access it on unpkg.

These aren't bright ideas, but hopefully it helps. Does what I said make sense?

**Comment by miguelslp** [comment]
Hi Jared,

Thank you for your quick and thoughtful response. I will experiment with the available files for the library I'm aiming at (uland), it might have the file I need. 

I was trying to avoid more compilation steps and tools for the sake of simplification and I'm grateful an option like you provide exists. Otherwise, I've been experimenting with [ESM](https://cdn.esm.sh/) cdn and having better performance than unpkg while I am trying to set up this plugin.

Thanks

**Comment by jaredgorski** [comment]
I took a look at `uland` by just going to `https://unpkg.com/uland` and it automatically redirected me to [this file](https://unpkg.com/uland@0.6.3/min.js) at `https://unpkg.com/uland@0.6.3/min.js`. That file looks like it should work. Go ahead and see if it works for you.

The code for this plugin is embarrassingly simple... honestly, you could fork it and create your own version that interpolates the proper download URL [here](https://github.com/jaredgorski/eleventy-njk-unpkg-inliner/blob/master/src/unpkg-inliner.js#L2), or you could just copy my code into a custom plugin on your eleventy build.

Anyway, thanks for reaching out; hope this was helpful! I'll close the issue but feel free to reply if you have any questions.

**Comment by miguelslp** [comment]
Thank you, it was 🙂. I'll give it a try
